# Generated by Django 5.0.14 on 2026-05-25 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_profile_picture'),
    ]

    operations = []
