# Generated by Django 5.0.14 on 2026-04-27 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='activity_files/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.activity')),
            ],
            options={
                'db_table': 'activity_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='ActivityPhoto',
        ),
    ]
