# Generated by Django 5.0.14 on 2026-04-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activityfile_delete_activityphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfile',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
