# Generated by Django 5.0.14 on 2026-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tasksubmission_alter_work_category'),
    ]

    operations = []

