# Generated by Django 5.0.14 on 2026-05-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_uploaded_by_tasksubmission_submitted_by_and_more'),
        ('api', '0008_tasksubmission_status_deadline'),
    ]

    operations = [
    ]
