# Generated by Django 5.0.14 on 2026-05-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tasksubmission_status_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('creation', 'Creation'), ('implementation', 'Implementation')], default='engineering', max_length=20),
        ),
    ]
