# Generated by Django 5.0.14 on 2026-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
